language: python

python:
  - "2.7"
  - "3.6"

env:
  - DJANGO_VERSION="Django>=1.9,<1.10"
  - DJANGO_VERSION="Django>=1.10,<1.11"
  - DJANGO_VERSION="Django>=1.11,<1.12"
  - DJANGO_VERSION="Django>=2,<2.1"
  - DJANGO_VERSION="Django>=2.1,<2.2"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION="Django>=2,<2.1"
    - python: "2.7"
      env: DJANGO_VERSION="Django>=2.1,<2.2"

install:s
  - pip install -U pip
  - pip install -q "$DJANGO_VERSION"
  - pip install .
  - pip install -r requirements_test.txt

script: py.test --cov=service_status

after_success:
  - codecov
